### ISSUE TITLE
Support compressed file in sitemap

### ISSUE THREAD

**Issue by YazdanJahedi** [TurnerSoftware/SitemapTools#118]
Hi,
Some websites use compressed files in the sitemap instead of `.xml` files. 
for example consider this sitemap:  `https://www.digikala.com/sitemap.xml`.  As You can see the sitemap contains some `.gz` files.  
It is very nice if this project supports this types of sitemaps.
Thanks

**Comment by Turnerj** [comment]
Hey @YazdanJahedi - the library does support compressed sitemaps as long as there is appropriate content types returned by the server.

See: https://github.com/TurnerSoftware/SitemapTools/blob/4ac4cdbe4f09081fb6753e5c26f7a936600aa9cb/src/TurnerSoftware.SitemapTools/SitemapQuery.cs#L134C1-L136C95
