### ISSUE TITLE
Code Example or Documentation

### ISSUE THREAD

**Issue by kenofori** [TurnerSoftware/SitemapTools#19]
Hi there,

Thanks for this library, I'm myself unfamiliar with sitemaps but hopefully this lib seems to be able to solve my problem.

Can you please provide code examples for this just like you have for https://github.com/TurnerSoftware/RobotsExclusionTools
etc

What i want to do is provide few sitemap (xml based) links, where each sitemap itself will hv location to other sitemaps and so on finally reaching to actual records.

So what methods etc should i use for this?

Regards

**Comment by Turnerj** [comment]
Thanks for raising an issue! Completely agree, I should have documentation on how to use this - kinda surprised I forgot about this!

I'll try and write some documentation (both in the readme and in the code for Intellisense) in the next few days. I'll comment back here again once I have done that. 🙂

**Comment by Turnerj** [comment]
I've updated the readme with a basic example and added IntelliSense documentation for various methods and properties.

**Comment by kenofori** [comment]
@Turnerj Thanks for the update,
and sorry for being so dumb, assuming i have got all sitemap enteries.
var sitemapEntries = await sitemapQuery.GetAllSitemapsForDomainAsync("example.org");

now based on my little knoweldge, i read that a sitemap can itself have a sitemap eventually leading to actual links.

so if i want to log all the links, where will be those in a SitemapFile?

**Comment by Turnerj** [comment]
So `GetAllSitemapsForDomainAsync` will get all sitemaps by three methods:
- Getting the "expected" sitemap in the domain root (example.org/sitemap.xml)
- Getting any sitemaps referenced in the Robots.txt file
- From either of the two methods above, if they are sitemap index files (sitemap files that point to sitemap files), it will recursively search those.

This means the result from the function call is every individual sitemap file excluding sitemap index files. The result type of `IEnumerable<SitemapFile>` means to get all of the links specifically, you would go `sitemapFiles.SelectMany(e => e.Urls)` which is an enumerable of `SitemapEntry` objects (the ones that are specific links to pages with their priority and modified date etc).

Hope that helps!
